# Generated by Django 3.1.2 on 2020-10-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_order_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
